swagger: "2.0"
info:
  description: "Used to get details about codes and code lists stored by ONS.
  Codes are used to provide a common definition when presenting statistics
  with related categories. Codes are gathered in code lists, which may change over time
  to include new or different codes. The meaning of a code should not change over
  time, but new codes may be created where new meaning is required."
  version: "1.0.0"
  title: "Explore codes & lists"
  license:
    name: "Open Government Licence v3.0"
    url: "http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
basePath: "/v1"
tags:
- name: "Code List"
schemes:
- "http"
parameters:
  id:
    name: id
    description: "The ID of a code list"
    in: path
    type: string
    required: true
  codeId:
    name: code_id
    description: "The ID of the Code within a code list"
    in: path
    type: string
    required: true
  offset:
    name: offset
    description: "The offset from the start of results. This defaults to 0"
    in: query
    type: integer
  limit:
    name: limit
    description: "The maximum number of results to be returned. This defaults to 20"
    in: query
    type: integer
  query:
    name: q
    description: "Query all code lists"
    in: query
    type: string
paths:
  /code-lists:
    get:
      tags:
      - "Code List"
      summary: "Get a list of code lists"
      description: "Get a set of codes lists containing information about dimensions which are used for all datasets at the ONS"
      parameters:
      - $ref: '#/parameters/offset'
      - $ref: '#/parameters/limit'
      produces:
      - "application/json"
      responses:
        200:
          description: "A Json message containing a set of code lists"
          schema:
            $ref: '#/definitions/CodeLists'
        400:
          description: "Missing parameters within request"
        500:
          description: "Failed to process the request due to an internal error"
  /code-lists/{id}:
    get:
      tags:
      - "Code List"
      summary: "Get a code list"
      description: "Get information about a code list"
      parameters:
      - $ref: '#/parameters/id'
      produces:
      - "application/json"
      responses:
        200:
          description: "Json object containing information about the code list"
          schema:
            $ref: '#/definitions/CodeList'
        404:
          description: "Code list not found"
        500:
          description: "Failed to process the request due to an internal error"
  /code-lists/{id}/codes:
    get:
      tags:
       - "Code List"
      summary: "Get a list of all codes within a code list"
      description: "Get a list of codes within a code list type"
      parameters:
      - $ref: '#/parameters/id'
      - $ref: '#/parameters/offset'
      - $ref: '#/parameters/limit'
      produces:
      - "application/json"
      responses:
        200:
          description: "A Json message containing a list of Codes"
          schema:
            $ref: '#/definitions/Codes'
        404:
          description: "Code list not found"
        500:
          description: "Failed to process the request due to an internal error"
  /code-lists/{id}/codes/{code_id}:
    get:
      tags:
       - "Code List"
      summary: "Get a code"
      description: "Get information about a code within a code list"
      parameters:
      - $ref: '#/parameters/id'
      - $ref: '#/parameters/codeId'
      produces:
      - "application/json"
      responses:
        200:
          description: "Get in depth information about a code"
          schema:
            $ref: '#/definitions/CodeInformation'
        404:
          description: "Code list or code not found"
        500:
          description: "Failed to process the request due to an internal error"
definitions:
  CodeList:
    type: object
    properties:
      id:
        type: string
        description: "The id for the code list"
      name:
        type: string
        description: "The name of the code list"
      links:
        type: object
        properties:
          self:
            $ref: '#/definitions/Href'
          code:
            $ref: '#/definitions/Href'
  CodeLists:
    type: object
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/CodeList'
      number_of_results:
        type: integer
        description: "The number of results available"
  Code:
    type: object
    properties:
      code:
        type: string
        description: "The value of a code"
      label:
        type: string
        description: "A label used by the code"
      links:
        type: object
        properties:
          self:
            $ref: '#/definitions/Href'
          code_list:
            $ref: '#/definitions/Href'
  Codes:
    type: object
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/Code'
      number_of_results:
              type: integer
              description: "The number of results available"
  CodeInformation:
    type: object
    properties:
      id:
        type: string
        description: "The id for the code"
      name:
        type: string
        description: "The name for the code"
      information:
        type: object
        description: "Additional information about the code"
  Href:
    type: object
    properties:
      id:
        type: string
        description: "The id of the resource"
      href:
        type: string
        description: "The URL to the resource"
